exasol/test-db-builder-java

- doc/design.md
- doc/system_requirements.md
- doc/user_guide/user_guide.md
- src/main/java/com/exasol/dbbuilder/AbstractDatabaseObject.java
- src/main/java/com/exasol/dbbuilder/AbstractSchemaChild.java
- src/main/java/com/exasol/dbbuilder/AdapterScript.java
- src/main/java/com/exasol/dbbuilder/ConnectionDefinition.java
- src/main/java/com/exasol/dbbuilder/DatabaseObject.java
- src/main/java/com/exasol/dbbuilder/DatabaseObjectException.java
- src/main/java/com/exasol/dbbuilder/DatabaseObjectFactory.java
- src/main/java/com/exasol/dbbuilder/ExasolObjectFactory.java
- src/main/java/com/exasol/dbbuilder/Schema.java
- src/main/java/com/exasol/dbbuilder/Script.java
- src/main/java/com/exasol/dbbuilder/Table.java
- src/main/java/com/exasol/dbbuilder/User.java
- src/main/java/com/exasol/dbbuilder/VirtualSchema.java
- src/main/java/com/exasol/dbbuilder/objectwriter/DatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/objectwriter/ImmediateDatabaseObjectWriter.java
- src/test/java/com/exasol/dbbuilder/AttachToExistingObjectIT.java
- src/test/java/com/exasol/dbbuilder/DatabaseObjectCreationIT.java
> #12: Use existing database objects

- README.md
- doc/changes/changelog.md
- doc/changes/changes-1.0.1.md
- pom.xml
> #24: added maven plugins, updated dependencies, added changelog.md

- doc/changes/changes_1.1.0.md
- doc/design.md
- doc/system_requirements.md
- src/main/java/com/exasol/dbbuilder/dialects/AbstractImmediateDatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/Schema.java
- src/main/java/com/exasol/dbbuilder/dialects/Table.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/AdapterScript.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ConnectionDefinition.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolImmediateDatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolObjectFactory.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolSchema.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchema.java
- src/test/java/com/exasol/dbbuilder/dialects/AbstractDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/AbstractSchemaTest.java
- src/test/java/com/exasol/dbbuilder/dialects/TableTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/AdapterScriptTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ConnectionDefinitionTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchemaTest.java
> #33 Refactored requirement tracing

- doc/changes/changes_1.1.0.md
- src/main/java/com/exasol/dbbuilder/dialects/exasol/AdapterScript.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolImmediateDatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolSchema.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/AdapterScriptTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolSchemaTest.java
> #36 Loading adapter scripts from file

- .github/workflows/upload_release_asset.yml
- doc/changes/changes_1.1.0.md
> #38 Added GitHub workflow for automated release

- README.md
- doc/changes/changelog.md
- doc/changes/changes_2.1.0.md
- pom.xml
- src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlIdentifier.java
- src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlImmediateDatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlObjectFactory.java
- src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlSchema.java
- src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlUser.java
- src/test/java/com/exasol/dbbuilder/dialects/AbstractDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/mysql/MySQLDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlIdentifierTest.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlImmediateDatabaseObjectWriterTest.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlSchemaTest.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlUserTest.java
> #50: Added PostgreSQL dialect

- doc/changes/changes_2.1.0.md
- src/main/java/com/exasol/dbbuilder/dialects/AbstractSchema.java
- src/main/java/com/exasol/dbbuilder/dialects/Schema.java
> #56: Added createTableBuilder to the Schema interface

- doc/changes/changelog.md
- doc/changes/changes_3.0.0.md
- pom.xml
- src/main/java/com/exasol/dbbuilder/dialects/AbstractImmediateDatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/DatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/Table.java
- src/test/java/com/exasol/dbbuilder/dialects/TableTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/AttachToExistingObjectIT.java
> feature/59: Added bulk insert for tables

- doc/changes/changelog.md
- doc/changes/changes_3.0.1.md
- doc/user_guide/user_guide.md
> #64: Fixed typo in connection definition example

- doc/changes/changes_3.0.1.md
- doc/user_guide/user_guide.md
- pom.xml
> #58: Added UDF script creation examples to user guide

- doc/changes/changes_3.0.1.md
- pom.xml
- src/main/java/com/exasol/dbbuilder/dialects/exasol/BucketFsContentAdapterScriptBuilder.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/AdapterScriptTest.java
> #48: Added support for multiple jars in BucketFS content

- doc/changes/changelog.md
- doc/changes/changes_3.0.1.md
- doc/changes/changes_3.1.0.md
- pom.xml
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolImmediateDatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolStringLiteralEscaper.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolStringLiteralEscaperTest.java
> #70: Made `script.execute` robust against quotes

- doc/changes/changelog.md
- doc/changes/changes_3.1.1.md
- pom.xml
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolImmediateDatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/mysql/MySQLIdentifier.java
- src/main/java/com/exasol/dbbuilder/dialects/mysql/MySqlImmediateDatabaseObjectWriter.java
- src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlIdentifier.java
- src/test/java/com/exasol/dbbuilder/dialects/AbstractDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/mysql/MySQLDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/mysql/MySQLIdentifierTest.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlIdentifierTest.java
> #62: Fixed identifier quoting for PostgreSQL and MySQL

- doc/changes/changes_3.2.0.md
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ConnectionDefinition.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolObjectFactory.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolSchema.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/ExasolUser.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchema.java
- src/main/java/com/exasol/dbbuilder/dialects/mysql/MySqlObjectFactory.java
- src/main/java/com/exasol/dbbuilder/dialects/mysql/MySqlSchema.java
- src/main/java/com/exasol/dbbuilder/dialects/mysql/MySqlUser.java
- src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlObjectFactory.java
- src/main/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlSchema.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ConnectionDefinitionTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolImmediateDatabaseObjectWriterTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolSchemaTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolUserTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchemaTest.java
- src/test/java/com/exasol/dbbuilder/dialects/mysql/MySqlSchemaTest.java
- src/test/java/com/exasol/dbbuilder/dialects/mysql/MySqlUserTest.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlSchemaTest.java
> #55: Unified the interfaces for creation of dB Objects

- doc/changes/changes_3.2.0.md
- release_config.yml
> #82: Added release_config.yml

- doc/changes/changes_3.3.1.md
> #94: Replaced PR number with issue number.

- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_3.3.4.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/dbbuilder/dialects/mysql/MySQLDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/oracle/OracleDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlDatabaseObjectCreationAndDeletionIT.java
> #101: Upgrade dependencies

- .gitattributes
- .github/workflows/release_droid_upload_github_release_assets.yml
- .gitignore
- .project-keeper.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_3.4.0.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- release_config.yml
- src/main/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchema.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchemaTest.java
> Updated dependencies and added documentation

- .project-keeper.yml
- .vscode/settings.json
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_3.4.1.md
- pk_generated_parent.pom
- pom.xml
> #105: Upgrade dependencies

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .gitignore
- .project-keeper.yml
- .settings/org.eclipse.core.resources.prefs
- .settings/org.eclipse.m2e.core.prefs
- .settings/org.moreunit.core.prefs
- .settings/org.moreunit.prefs
- README.md
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_3.3.4.md
- doc/changes/changes_3.4.3.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/dbbuilder/dialects/mysql/MySQLDatabaseObjectCreationAndDeletionIT.java
- src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlDatabaseObjectCreationAndDeletionIT.java
> #112: Fix broken links

- doc/changes/changes_3.5.0.md
- src/main/java/com/exasol/dbbuilder/dialects/Table.java
- src/main/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchema.java
- src/main/java/com/exasol/dbbuilder/dialects/oracle/OracleTable.java
- src/test/java/com/exasol/dbbuilder/dialects/TableTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/ExasolScriptTest.java
- src/test/java/com/exasol/dbbuilder/dialects/exasol/VirtualSchemaTest.java
- src/test/java/com/exasol/dbbuilder/dialects/oracle/OracleTableTest.java
> #53 Move write() out of constructor

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/dependencies_check.yml
- .github/workflows/release_droid_prepare_original_checksum.yml
- .github/workflows/release_droid_print_quick_checksum.yml
- .github/workflows/release_droid_release_on_maven_central.yml
- .github/workflows/release_droid_upload_github_release_assets.yml
- .project-keeper.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_3.5.1.md
- pk_generated_parent.pom
- pom.xml
> #120 Upgrade dependencies
